# Generated by Django 4.1.2 on 2023-03-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
