# Generated by Django 4.1.2 on 2023-05-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_profile_pic_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='accounts'),
        ),
    ]
